export const VITALIDAD  = "Vitalidad"; 
export const LADRADOR   = "Ladrador"; 
export const VIGILANCIA = "Instinto de Vigilancia"; 
export const PROTECCION = "Protección";
export const RELACIONNI = "Relación con los niños"; 
export const RELACIONPE = "Relación con los perros"; 
export const APRENDIZAJE = "Cap. de aprendizaje"; 
export const EJERCICIO = "Necesidad ejercicio"; 

const URLFULLSTAR = "/img/estrella-con-relleno.png";
const ALLFULLSTAR = "S";
const URLEMPTYSTAR = "/img/estrella-sin-relleno.png";
const ALLEMPTYSTAR = "N";

const FULLSTART = [URLFULLSTAR, ALLFULLSTAR ];
const EMPTYSTAR = [URLEMPTYSTAR, ALLEMPTYSTAR ];

const SCOREVITALIDADBD   = [FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR ];
const SCORELADRADORBD    = [FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR, EMPTYSTAR ];
const SCOREVIGILANCIABD  = [FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR, EMPTYSTAR ];
const SCOREPROTECCIONBD  = [FULLSTART, EMPTYSTAR, EMPTYSTAR, EMPTYSTAR, EMPTYSTAR ];
const SCORERELACIONNIBD  = [FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR ];
const SCORERELACIONPEBD  = [FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR ];
const SCOREAPRENDIZAJEBD = [FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR, EMPTYSTAR ];
const SCOREEJERCICIOBD   = [FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR, EMPTYSTAR ];

const SCOREVITALIDADSC   = [FULLSTART, FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR ];
const SCORELADRADORSC    = [FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR ];
const SCOREVIGILANCIASC  = [FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR ];
const SCOREPROTECCIONSC  = [FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR, EMPTYSTAR ];
const SCORERELACIONNISC  = [FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR ];
const SCORERELACIONPESC  = [FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR ];
const SCOREAPRENDIZAJSC  = [FULLSTART, FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR ];
const SCOREEJERCICIOSC   = [FULLSTART, FULLSTART, FULLSTART, EMPTYSTAR, EMPTYSTAR ];

export const SCOREBULLDOG = [ SCOREVITALIDADBD,   SCORELADRADORBD,   SCOREVIGILANCIABD, 
                              SCOREPROTECCIONBD,  SCORERELACIONNIBD, SCORERELACIONPEBD,
                              SCOREAPRENDIZAJEBD, SCOREEJERCICIOBD  
                            ];
export const SCORESCHNAUZER = [ SCOREVITALIDADSC,  SCORELADRADORSC,   SCOREVIGILANCIASC,
                                SCOREPROTECCIONSC, SCORERELACIONNISC, SCORERELACIONPESC,
                                SCOREAPRENDIZAJSC, SCOREEJERCICIOSC
                              ];                       